# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Phoenix's Nest
email: phoenixgward@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Base site created during Codecademy course, may evolve into personal site over time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phoenixgward.com" # the base hostname & protocol for your site
twitter_username: phoenixgward
github_username:  phoenixgward

# Build settings
markdown: kramdown
